FROM node:24-bookworm-slim

ENV NODE_ENV=production
WORKDIR /app

COPY api/package.json ./package.json
COPY api/package-lock.json ./package-lock.json
RUN npm ci

COPY api/tsconfig.json ./tsconfig.json
COPY api/worker.ts ./worker.ts
COPY api/lib/openada/*.ts ./lib/openada/

CMD ["npm", "run", "worker"]
